apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Name }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ .Size }}
  nfs:
    path: {{ .Path }}
    server: {{ .Server }}
  persistentVolumeReclaimPolicy: {{ .ReclaimPolicy }}
